services:
  smartload:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartload:latest
    container_name: smartload-container
    ports:
      - "8080:8080"
    restart: unless-stopped
